<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LPTP120" failures="1" tests="2" name="Error Validation Test" time="19.874" errors="0" timestamp="2024-10-20T23:00:15 IST">
  <testcase classname="rahulshettyacademy.tests.ErrorValidationTest" name="LoginErrorValidation" time="1.178"/>
  <testcase classname="rahulshettyacademy.tests.ErrorValidationTest" name="ProductErrorValidation" time="6.418">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at rahulshettyacademy.tests.ErrorValidationTest.ProductErrorValidation(ErrorValidationTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validation Test -->
